name: Build Shattered Pixel Dungeon APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Установка окружения
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    # Кэширование Gradle для ускорения сборки
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: gradle-

    # Сборка APK
    - name: Build APK
      run: ./gradlew assembleDebug

    # Загрузка APK как артефакт
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: ShatteredPD-Debug-APK
        path: android/build/outputs/apk/debug/*.apk
