name: Build Shattered Pixel Dungeon APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Проверка исходного кода
    - name: Checkout repository
      uses: actions/checkout@v4  # Обновлено до последней версии

    # Установка JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v4  # Обновлено до последней версии
      with:
        java-version: '11'
        distribution: 'temurin'  # Используем Temurin для надёжности

    # Установка Android SDK
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3  # Обновлено до последней версии

    # Кэширование Gradle
    - name: Cache Gradle
      uses: actions/cache@v4  # Обновлено до последней версии
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: gradle-

    # Сборка отладочного APK
    - name: Build Debug APK
      run: ./gradlew assembleDebug

    # Загрузка APK как артефакт
    - name: Upload APK
      uses: actions/upload-artifact@v4  # Явно указываем версию v4
      with:
        name: ShatteredPD-Debug-APK
        path: android/build/outputs/apk/debug/*.apk
        retention-days: 7  # Храним артефакт 7 дней
