name: Build Shattered Pixel Dungeon APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Проверка исходного кода
    - name: Checkout repository
      uses: actions/checkout@v4

    # Установка JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Установка Android SDK
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: '12.0'

    # Принятие лицензий Android SDK
    - name: Accept Android SDK Licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    # Установка прав на выполнение для gradlew
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    # Кэширование Gradle
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: gradle-

    # Очистка перед сборкой
    - name: Clean Gradle
      run: ./gradlew clean

    # Сборка отладочного APK
    - name: Build Debug APK
      run: ./gradlew assembleDebug

    # Загрузка APK как артефакт
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ShatteredPD-Debug-APK
        path: android/build/outputs/apk/debug/*.apk
        retention-days: 7
